version: '3.4'

services:
  db:
    image: postgres
    network_mode: "host"
    security_opt:
      - seccomp:unconfined
    env_file:
      - '.env.dev'

  web:
    build: .
    volumes:
    - .:/code
    network_mode: "host"
    depends_on:
      - db
    env_file:
      - '.env.dev'