"""Create snapshot

Revision ID: d67b6a9c42c3
Revises: 
Create Date: 2023-03-06 19:11:06.491533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d67b6a9c42c3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snapshot",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("text", sa.String(length=5000), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snapshot")
    # ### end Alembic commands ###
